BEGIN;
-- Dried Thyme [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Dried Thyme' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 1138), energy_kcal = COALESCE(energy_kcal, 276), fat = COALESCE(fat, 7.4), saturates = COALESCE(saturates, 2.7), carbohydrate = COALESCE(carbohydrate, 26.9), sugars = COALESCE(sugars, 1.7), protein = COALESCE(protein, 9.1), fibre = COALESCE(fibre, 37.0), salt = COALESCE(salt, 0.06) WHERE id = 62 AND name = 'Dried Thyme';
-- Duck [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Duck' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 769), energy_kcal = COALESCE(energy_kcal, 184), fat = COALESCE(fat, 10.0), saturates = COALESCE(saturates, 3.5), carbohydrate = COALESCE(carbohydrate, 0), sugars = COALESCE(sugars, 0), protein = COALESCE(protein, 23.5), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 0.15) WHERE id = 24 AND name = 'Duck';
-- Courgettes [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Courgette' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 71), energy_kcal = COALESCE(energy_kcal, 17), fat = COALESCE(fat, 0.3), saturates = COALESCE(saturates, 0.1), carbohydrate = COALESCE(carbohydrate, 1.8), sugars = COALESCE(sugars, 1.7), protein = COALESCE(protein, 1.2), fibre = COALESCE(fibre, 1.0), salt = COALESCE(salt, 0.02) WHERE id = 16 AND name = 'Courgettes';
-- Garlic Cloves fresh peeled [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Garlic' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 620), energy_kcal = COALESCE(energy_kcal, 149), fat = COALESCE(fat, 0.5), saturates = COALESCE(saturates, 0.1), carbohydrate = COALESCE(carbohydrate, 29.3), sugars = COALESCE(sugars, 1.0), protein = COALESCE(protein, 6.4), fibre = COALESCE(fibre, 2.1), salt = COALESCE(salt, 0.04) WHERE id = 63 AND name = 'Garlic Cloves fresh peeled';
-- Gherkin (drained weight) [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Gherkin' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 67), energy_kcal = COALESCE(energy_kcal, 16), fat = COALESCE(fat, 0.1), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 2.0), sugars = COALESCE(sugars, 1.1), protein = COALESCE(protein, 0.5), fibre = COALESCE(fibre, 1.0), salt = COALESCE(salt, 1.6) WHERE id = 57 AND name = 'Gherkin (drained weight)';
-- Ground Cumin [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Ground Cumin' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 1567), energy_kcal = COALESCE(energy_kcal, 375), fat = COALESCE(fat, 22.3), saturates = COALESCE(saturates, 1.5), carbohydrate = COALESCE(carbohydrate, 33.7), sugars = COALESCE(sugars, 2.3), protein = COALESCE(protein, 17.8), fibre = COALESCE(fibre, 10.5), salt = COALESCE(salt, 0.17) WHERE id = 73 AND name = 'Ground Cumin';
-- Honey  [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Honey' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 1381), energy_kcal = COALESCE(energy_kcal, 329), fat = COALESCE(fat, 0), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 81.5), sugars = COALESCE(sugars, 81.5), protein = COALESCE(protein, 0.3), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 0.01) WHERE id = 97 AND name = 'Honey ';
-- Mushrooms [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Mushrooms' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 55), energy_kcal = COALESCE(energy_kcal, 13), fat = COALESCE(fat, 0.5), saturates = COALESCE(saturates, 0.1), carbohydrate = COALESCE(carbohydrate, 0.4), sugars = COALESCE(sugars, 0.2), protein = COALESCE(protein, 1.8), fibre = COALESCE(fibre, 1.0), salt = COALESCE(salt, 0.02) WHERE id = 14 AND name = 'Mushrooms';
-- Onion Powder [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Onion Powder' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 1431), energy_kcal = COALESCE(energy_kcal, 341), fat = COALESCE(fat, 1.0), saturates = COALESCE(saturates, 0.2), carbohydrate = COALESCE(carbohydrate, 79.1), sugars = COALESCE(sugars, 6.6), protein = COALESCE(protein, 10.4), fibre = COALESCE(fibre, 15.2), salt = COALESCE(salt, 0.08) WHERE id = 87 AND name = 'Onion Powder';
-- Smoked paprika (old) [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Smoked Paprika' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 1172), energy_kcal = COALESCE(energy_kcal, 282), fat = COALESCE(fat, 12.9), saturates = COALESCE(saturates, 2.1), carbohydrate = COALESCE(carbohydrate, 34.8), sugars = COALESCE(sugars, 10.3), protein = COALESCE(protein, 14.1), fibre = COALESCE(fibre, 34.9), salt = COALESCE(salt, 0.08) WHERE id = 128 AND name = 'Smoked paprika (old)';
-- Spring Onions [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Spring Onion' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 138), energy_kcal = COALESCE(energy_kcal, 33), fat = COALESCE(fat, 0.2), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 5.7), sugars = COALESCE(sugars, 2.8), protein = COALESCE(protein, 1.8), fibre = COALESCE(fibre, 2.6), salt = COALESCE(salt, 0.04) WHERE id = 15 AND name = 'Spring Onions';
-- Pastrami (Sliced) [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Pastrami (Beef, Salt, Sugar, Spices, Smoke Flavouring)' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 560), energy_kcal = COALESCE(energy_kcal, 133), fat = COALESCE(fat, 4.8), saturates = COALESCE(saturates, 1.6), carbohydrate = COALESCE(carbohydrate, 2.0), sugars = COALESCE(sugars, 1.8), protein = COALESCE(protein, 21.0), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 2.5) WHERE id = 193 AND name = 'Pastrami (Sliced)';
-- Balsamic Glaze [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Balsamic Glaze (Balsamic Vinegar of Modena (Wine Vinegar, Grape Must), Glucose-Fructose Syrup)' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 754), energy_kcal = COALESCE(energy_kcal, 178), fat = COALESCE(fat, 0), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 43.0), sugars = COALESCE(sugars, 38.0), protein = COALESCE(protein, 0.5), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 0.08) WHERE id = 28 AND name = 'Balsamic Glaze';
-- Pepperoni [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Pepperoni (Pork, Spices, Salt, Dextrose, Garlic Powder, Smoke Flavouring)' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 1979), energy_kcal = COALESCE(energy_kcal, 476), fat = COALESCE(fat, 40.2), saturates = COALESCE(saturates, 14.8), carbohydrate = COALESCE(carbohydrate, 3.1), sugars = COALESCE(sugars, 1.1), protein = COALESCE(protein, 24.8), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 3.6) WHERE id = 11 AND name = 'Pepperoni';
-- Chicken breast fillet strips [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Chicken Breast' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 460), energy_kcal = COALESCE(energy_kcal, 110), fat = COALESCE(fat, 1.3), saturates = COALESCE(saturates, 0.3), carbohydrate = COALESCE(carbohydrate, 0), sugars = COALESCE(sugars, 0), protein = COALESCE(protein, 23.1), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 0.15) WHERE id = 251 AND name = 'Chicken breast fillet strips';
-- Salt [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 0), energy_kcal = COALESCE(energy_kcal, 0), fat = COALESCE(fat, 0), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 0), sugars = COALESCE(sugars, 0), protein = COALESCE(protein, 0), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 99.8) WHERE id = 3 AND name = 'Salt';
-- Olive Oil [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 3701), energy_kcal = COALESCE(energy_kcal, 884), fat = COALESCE(fat, 100), saturates = COALESCE(saturates, 14.2), carbohydrate = COALESCE(carbohydrate, 0), sugars = COALESCE(sugars, 0), protein = COALESCE(protein, 0), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 0) WHERE id = 25 AND name = 'Olive Oil';
-- Yeast [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 1296), energy_kcal = COALESCE(energy_kcal, 310), fat = COALESCE(fat, 4), saturates = COALESCE(saturates, 0.6), carbohydrate = COALESCE(carbohydrate, 41.2), sugars = COALESCE(sugars, 0), protein = COALESCE(protein, 40.4), fibre = COALESCE(fibre, 26.9), salt = COALESCE(salt, 0.12) WHERE id = 33 AND name = 'Yeast';
-- Tap Water [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 0), energy_kcal = COALESCE(energy_kcal, 0), fat = COALESCE(fat, 0), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 0), sugars = COALESCE(sugars, 0), protein = COALESCE(protein, 0), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 0) WHERE id = 95 AND name = 'Tap Water';
-- Mozzarella [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 1132), energy_kcal = COALESCE(energy_kcal, 271), fat = COALESCE(fat, 17.7), saturates = COALESCE(saturates, 11.1), carbohydrate = COALESCE(carbohydrate, 3.1), sugars = COALESCE(sugars, 1.4), protein = COALESCE(protein, 25.3), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 0.63) WHERE id = 47 AND name = 'Mozzarella';
-- Passata (Rodolfi) [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 109), energy_kcal = COALESCE(energy_kcal, 26), fat = COALESCE(fat, 0.1), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 4.3), sugars = COALESCE(sugars, 3.8), protein = COALESCE(protein, 1.3), fibre = COALESCE(fibre, 1.0), salt = COALESCE(salt, 0.04) WHERE id = 26 AND name = 'Passata (Rodolfi)';
-- Tomato Puree (paste) [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 347), energy_kcal = COALESCE(energy_kcal, 82), fat = COALESCE(fat, 0.4), saturates = COALESCE(saturates, 0.1), carbohydrate = COALESCE(carbohydrate, 13.1), sugars = COALESCE(sugars, 11.5), protein = COALESCE(protein, 4.3), fibre = COALESCE(fibre, 4.1), salt = COALESCE(salt, 0.17) WHERE id = 37 AND name = 'Tomato Puree (paste)';
-- Red Onions [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 163), energy_kcal = COALESCE(energy_kcal, 39), fat = COALESCE(fat, 0.1), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 7.9), sugars = COALESCE(sugars, 5.6), protein = COALESCE(protein, 1.2), fibre = COALESCE(fibre, 1.7), salt = COALESCE(salt, 0.01) WHERE id = 13 AND name = 'Red Onions';
-- Oregano [script]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 1087), energy_kcal = COALESCE(energy_kcal, 265), fat = COALESCE(fat, 4.3), saturates = COALESCE(saturates, 1.6), carbohydrate = COALESCE(carbohydrate, 26.0), sugars = COALESCE(sugars, 4.1), protein = COALESCE(protein, 9.0), fibre = COALESCE(fibre, 42.5), salt = COALESCE(salt, 0.06) WHERE id = 43 AND name = 'Oregano';
-- American Mustard [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'American Mustard (Water, Spirit Vinegar, Mustard Seed, Salt, Turmeric, Paprika, Garlic Powder)' ELSE label_declaration END, allergens = CASE WHEN allergens = '[]'::jsonb THEN '["mustard"]'::jsonb ELSE allergens END WHERE id = 139 AND name = 'American Mustard';
-- Hoisin Sauce [script]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Hoisin Sauce (Water, Sugar, Soya Beans, Modified Corn Starch, Salt, Sesame Oil, Garlic, Chilli, Spices)' ELSE label_declaration END, allergens = CASE WHEN allergens = '[]'::jsonb THEN '["soybeans","sesame"]'::jsonb ELSE allergens END WHERE id = 49 AND name = 'Hoisin Sauce';
-- Macaroni [ref]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'Macaroni (Durum WHEAT Semolina)' ELSE label_declaration END, allergens = CASE WHEN allergens = '[]'::jsonb THEN '["cereals_containing_gluten"]'::jsonb ELSE allergens END, energy_kj = COALESCE(energy_kj, 1502), energy_kcal = COALESCE(energy_kcal, 354), fat = COALESCE(fat, 1.5), saturates = COALESCE(saturates, 0.3), carbohydrate = COALESCE(carbohydrate, 71.6), sugars = COALESCE(sugars, 3.5), protein = COALESCE(protein, 12.3), fibre = COALESCE(fibre, 3.1), salt = COALESCE(salt, 0.01) WHERE id = 194 AND name = 'Macaroni';
-- Plain Flour [ref]
UPDATE ingredients SET label_declaration = CASE WHEN label_declaration IS NULL OR label_declaration = '' THEN 'WHEAT Flour' ELSE label_declaration END, energy_kj = COALESCE(energy_kj, 1450), energy_kcal = COALESCE(energy_kcal, 341), fat = COALESCE(fat, 1.4), saturates = COALESCE(saturates, 0.2), carbohydrate = COALESCE(carbohydrate, 69.7), sugars = COALESCE(sugars, 1.5), protein = COALESCE(protein, 9.4), fibre = COALESCE(fibre, 3.1), salt = COALESCE(salt, 0.01) WHERE id = 98 AND name = 'Plain Flour';
-- Panko Breadcrumbs [ref]
UPDATE ingredients SET allergens = CASE WHEN allergens = '[]'::jsonb THEN '["cereals_containing_gluten"]'::jsonb ELSE allergens END, energy_kj = COALESCE(energy_kj, 1495), energy_kcal = COALESCE(energy_kcal, 353), fat = COALESCE(fat, 1.8), saturates = COALESCE(saturates, 0.4), carbohydrate = COALESCE(carbohydrate, 71.9), sugars = COALESCE(sugars, 4.4), protein = COALESCE(protein, 11.7), fibre = COALESCE(fibre, 4.0), salt = COALESCE(salt, 1.05) WHERE id = 85 AND name = 'Panko Breadcrumbs';
-- Lemon Juice [ref]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 104), energy_kcal = COALESCE(energy_kcal, 25), fat = COALESCE(fat, 0.3), saturates = COALESCE(saturates, 0.1), carbohydrate = COALESCE(carbohydrate, 1.6), sugars = COALESCE(sugars, 1.6), protein = COALESCE(protein, 0.3), fibre = COALESCE(fibre, 0.1), salt = COALESCE(salt, 0.01) WHERE id = 55 AND name = 'Lemon Juice';
-- Red Kidney Beans in Water [ref]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 420), energy_kcal = COALESCE(energy_kcal, 100), fat = COALESCE(fat, 0.6), saturates = COALESCE(saturates, 0.1), carbohydrate = COALESCE(carbohydrate, 13.8), sugars = COALESCE(sugars, 0.5), protein = COALESCE(protein, 6.9), fibre = COALESCE(fibre, 6.2), salt = COALESCE(salt, 0.03) WHERE id = 265 AND name = 'Red Kidney Beans in Water';
-- Dijon Mustard [ref]
UPDATE ingredients SET allergens = CASE WHEN allergens = '[]'::jsonb THEN '["mustard"]'::jsonb ELSE allergens END WHERE id = 144 AND name = 'Dijon Mustard';
-- Worcestershire Sauce [ref]
UPDATE ingredients SET energy_kj = COALESCE(energy_kj, 374), energy_kcal = COALESCE(energy_kcal, 88), fat = COALESCE(fat, 0), saturates = COALESCE(saturates, 0), carbohydrate = COALESCE(carbohydrate, 19.0), sugars = COALESCE(sugars, 15.5), protein = COALESCE(protein, 1.1), fibre = COALESCE(fibre, 0), salt = COALESCE(salt, 2.5) WHERE id = 266 AND name = 'Worcestershire Sauce';
COMMIT;
