import { Router, type IRouter, type Request, type Response } from "express";
import { pool } from "@workspace/db";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const router: IRouter = Router();

const SEED_FILE = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../scripts/prod-seed.sql",
);

/**
 * POST /api/admin/apply-seed
 *
 * Applies scripts/prod-seed.sql (generated by `pnpm export-seed`) to the
 * current database inside an explicit transaction with ROLLBACK on error.
 *
 * Auth: Authorization: Bearer <MIGRATION_TOKEN>.
 * If MIGRATION_TOKEN is not set in the environment, the endpoint returns 404
 * (effectively disabled).  Wrong token returns 403.
 *
 * Response:
 *   200  { success: true,  tablesSeeded: string[] }
 *   500  { success: false, error: string }
 *
 * Usage:
 *   export MIGRATION_TOKEN=your-secret
 *   curl -X POST https://YOUR_API/api/admin/apply-seed \
 *        -H "Authorization: Bearer $MIGRATION_TOKEN"
 */
router.post("/apply-seed", async (req: Request, res: Response) => {
  // ── Auth: MIGRATION_TOKEN ───────────────────────────────────────────────────
  const token = process.env["MIGRATION_TOKEN"];
  if (!token) {
    // Not configured → treat as non-existent endpoint
    res.status(404).json({ success: false, error: "Not found" });
    return;
  }
  const authHeader = req.headers["authorization"];
  if (!authHeader || authHeader !== `Bearer ${token}`) {
    res.status(403).json({ success: false, error: "Forbidden" });
    return;
  }

  // ── Read seed file from disk ────────────────────────────────────────────────
  let sqlBody: string;
  try {
    sqlBody = readFileSync(SEED_FILE, "utf-8");
  } catch {
    res.status(404).json({ success: false, error: "Seed file not found on server" });
    return;
  }

  // Derive seeded table names from "-- TABLE: tableName" markers in the SQL
  const tablesSeeded = [...sqlBody.matchAll(/^-- TABLE:\s+(\S+)/gm)].map(m => m[1]);

  // ── Execute in an explicit transaction ──────────────────────────────────────
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(sqlBody);
    await client.query("COMMIT");
    res.json({ success: true, tablesSeeded });
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    const message = err instanceof Error ? err.message : String(err);
    console.error("[apply-seed] ROLLBACK — seed failed:", message);
    res.status(500).json({ success: false, error: message });
  } finally {
    client.release();
  }
});

export default router;
