import { Router, type IRouter, type Request, type Response } from "express";
import { pool } from "@workspace/db";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const router: IRouter = Router();

const SEED_FILE = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../scripts/prod-seed.sql",
);

/**
 * POST /api/admin/apply-seed
 *
 * Applies scripts/prod-seed.sql (generated by `pnpm export-seed`) to the
 * current database inside an explicit transaction.  Any error causes a full
 * ROLLBACK and a 500 response.
 *
 * Auth: requires the Authorization header to match the MIGRATION_TOKEN secret.
 * If MIGRATION_TOKEN is not set in the environment the endpoint returns 404,
 * effectively disabling it.
 *
 * Usage:
 *   export MIGRATION_TOKEN=your-secret
 *   curl -X POST https://YOUR_API/api/admin/apply-seed \
 *        -H "Authorization: Bearer $MIGRATION_TOKEN"
 *
 * WARNING: The seed file uses TRUNCATE … CASCADE and is intended for a fresh
 * production database.  Read MIGRATION.md before running.
 */
router.post("/apply-seed", async (req: Request, res: Response) => {
  // -- Auth: MIGRATION_TOKEN ------------------------------------------------
  const token = process.env["MIGRATION_TOKEN"];
  if (!token) {
    // Not configured → treat as non-existent endpoint
    res.status(404).json({ error: "Not found" });
    return;
  }
  const authHeader = req.headers["authorization"];
  if (!authHeader || authHeader !== `Bearer ${token}`) {
    res.status(403).json({ error: "Forbidden" });
    return;
  }

  // -- Read seed file from disk -------------------------------------------
  let sqlBody: string;
  try {
    sqlBody = readFileSync(SEED_FILE, "utf-8");
  } catch {
    res.status(404).json({ error: "Seed file not found on server" });
    return;
  }

  // -- Execute in an explicit transaction -----------------------------------
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(sqlBody);
    await client.query("COMMIT");
    res.json({ ok: true, message: "Seed applied successfully." });
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    const message = err instanceof Error ? err.message : String(err);
    console.error("[apply-seed] ROLLBACK — seed failed:", message);
    res.status(500).json({ error: "Seed failed — transaction rolled back", detail: message });
  } finally {
    client.release();
  }
});

export default router;
